version: '3'

services:
  postgres:
    container_name: notas_api
    image: postgres:16-alpine
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data 
    ports:
      - 5432:5432

